### ISSUE TITLE
Update to latest mongodb-connector causes problems

### ISSUE THREAD

**Issue by eisverticker** [transcriba/transcriba#3]
While trying to update all the dependencies to the latest version an error occured using loopback-connector-mongodb >= 1.18 (1.17 still works). 
After update it was not possible to use the include filter for getting user roles anymore.

**Comment by eisverticker** [comment]
It is also not possible to use the 3.x versions. Same problem there

**Comment by eisverticker** [comment]
https://github.com/strongloop/loopback-connector-mongodb/issues/363#issuecomment-297437024

**Comment by eisverticker** [comment]
for now the only solution is to set the strictObjectIdCoercionFlag on the RoleMapping relation

**Comment by kuongknight** [comment]
although I set strictObjectIdCoercionFlag for RoleMapping, I still found this issue:

> "loopback": "^3.18.1",
> "loopback-boot": "^2.6.5",
> "loopback-connector-mongodb": "^3.4.1",
> "loopback-connector-redis": "^0.1.0",
> "loopback-datasource-juggler": "^3.15.0"
